spring.application.name=RideSync Backend

# ===============================
# Database Configuration
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/ridesync_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Root@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ===============================
# Security / JWT
# ===============================
ridesync.app.jwt-secret=R1d3SynC_Sup3r_S3cur3_JWT_Secret_Key_That_Is_Definitely_More_Than_64_Bytes_Long_2026_Project

ridesync.app.jwt-expiration-ms=86400000

spring.main.banner-mode=off
logging.level.org.springframework.security=INFO
